[package]
name = "p3-koala-bear"
description = "Field extensions and optimized Poseidon2 implementations using the KoalaBear field with SIMD support."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
p3-field.workspace = true
p3-monty-31.workspace = true
p3-poseidon2.workspace = true
p3-symmetric.workspace = true

rand.workspace = true

[dev-dependencies]
p3-dft.workspace = true
p3-field-testing.workspace = true
p3-util.workspace = true

criterion.workspace = true
num-bigint.workspace = true
rand.workspace = true
rand_xoshiro.workspace = true
serde_json.workspace = true

[features]
nightly-features = ["p3-monty-31/nightly-features"]

[[bench]]
name = "bench_field"
harness = false

[[bench]]
name = "extension"
harness = false
