[package]
name = "p3-koala-bear"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field.workspace = true
p3-monty-31.workspace = true
p3-poseidon2.workspace = true
p3-symmetric.workspace = true
rand.workspace = true

[dev-dependencies]
p3-dft.workspace = true
p3-field-testing.workspace = true
p3-util.workspace = true

num-bigint.workspace = true
rand.workspace = true
criterion.workspace = true
serde_json.workspace = true
rand_xoshiro.workspace = true

[features]
nightly-features = ["p3-monty-31/nightly-features"]

[[bench]]
name = "bench_field"
harness = false

[[bench]]
name = "extension"
harness = false
