[package]
name = "p3-maybe-rayon"
description = "Feature-gated wrapper around rayon"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rayon = { workspace = true, optional = true }

[features]
parallel = ["rayon"]
