[package]
name = "p3-maybe-rayon"
description = "Feature-gated wrapper around rayon"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2024"

[features]
parallel = ["rayon"]

[dependencies]
rayon = { workspace = true, optional = true }
