[package]
name = "p3-tensor-pcs"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-brakedown = { path = "../brakedown" }
p3-challenger = { path = "../challenger" }
p3-code = { path = "../code" }
p3-commit = { path = "../commit" }
p3-field = { path = "../field" }
p3-matrix = { path = "../matrix" }
p3-util = { path = "../util" }
