[package]
name = "p3-lookup"
description = "LogUp: Logarithmic lookup arguments and multiset equality checks with multiplicities support."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
hashbrown = { workspace = true }
itertools.workspace = true
p3-air = { workspace = true }
p3-field = { workspace = true }
p3-matrix = { workspace = true }
p3-maybe-rayon = { workspace = true }
p3-uni-stark = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
criterion.workspace = true
p3-baby-bear = { path = "../baby-bear" }
p3-challenger = { path = "../challenger" }
p3-commit = { path = "../commit" }
p3-dft = { path = "../dft" }
p3-fri = { path = "../fri" }
p3-goldilocks = { path = "../goldilocks" }
p3-merkle-tree = { path = "../merkle-tree" }
p3-symmetric = { path = "../symmetric" }
rand = { workspace = true }

[features]
default = []
parallel = ["p3-maybe-rayon/parallel"]

[[bench]]
name = "logup"
harness = false

[lints]
workspace = true
