[package]
name = "p3-monolith"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
generic-array = "1.0"
p3-field = { path = "../field" }
p3-mersenne-31 = { path = "../mersenne-31" }
p3-mds = { path = "../mds" }
p3-symmetric = { path = "../symmetric" }
sha3 = "0.10"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "permute"
harness = false
