[package]
name = "p3-monolith"
description = "Plonky3 is a toolkit for implementing polynomial IOPs (PIOPs), such as PLONK and STARKs."
version = "0.1.6-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
generic-array = "1.0"
p3-field = { path = "../field", version = "0.1.6-succinct" }
p3-goldilocks = { path = "../goldilocks", version = "0.1.6-succinct" }
p3-mersenne-31 = { path = "../mersenne-31", version = "0.1.6-succinct" }
p3-mds = { path = "../mds", version = "0.1.6-succinct" }
p3-symmetric = { path = "../symmetric", version = "0.1.6-succinct" }
sha3 = "0.10"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "permute"
harness = false
