[package]
name = "p3-monolith"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field.workspace = true
p3-mersenne-31.workspace = true
p3-mds.workspace = true
p3-symmetric.workspace = true
sha3.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "permute"
harness = false
