[package]
name = "p3-monolith"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
generic-array = "1.0"
p3-field = { path = "../field", version = "0.2.0" }
p3-mersenne-31 = { path = "../mersenne-31", version = "0.2.0" }
p3-mds = { path = "../mds", version = "0.2.0" }
p3-symmetric = { path = "../symmetric", version = "0.2.0" }
sha3 = "0.10"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "permute"
harness = false
