[package]
name = "p3-poly"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-dft.workspace = true
p3-field.workspace = true
p3-matrix.workspace = true
itertools.workspace = true
rand = { workspace = true, optional = true }
rand_chacha = { workspace = true, optional = true }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }

[dev-dependencies]
p3-baby-bear.workspace = true
p3-goldilocks.workspace = true
rand.workspace = true
rand_chacha.workspace = true

[features]
test-utils = ["dep:rand", "dep:rand_chacha" ]
