[package]
name = "p3-fri"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-challenger = { path = "../challenger" }
p3-commit = { path = "../commit" }
p3-field = { path = "../field" }
p3-ldt = { path = "../ldt" }
p3-matrix = { path = "../matrix" }
itertools = "0.10.5"
