[package]
name = "p3-fri"
description = "Plonky3 is a toolkit for implementing polynomial IOPs (PIOPs), such as PLONK and STARKs."
version = "0.1.5-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-challenger = { path = "../challenger", version = "0.1.5-succinct" }
p3-commit = { path = "../commit", version = "0.1.5-succinct" }
p3-dft = { path = "../dft", version = "0.1.5-succinct" }
p3-field = { path = "../field", version = "0.1.5-succinct" }
p3-interpolation = { path = "../interpolation", version = "0.1.5-succinct" }
p3-matrix = { path = "../matrix", version = "0.1.5-succinct" }
p3-maybe-rayon = { path = "../maybe-rayon", version = "0.1.5-succinct" }
p3-util = { path = "../util", version = "0.1.5-succinct" }
itertools = "0.12.0"
tracing = "0.1.37"
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }

[dev-dependencies]
p3-baby-bear = { path = "../baby-bear", version = "0.1.5-succinct" }
p3-dft = { path = "../dft", version = "0.1.5-succinct" }
p3-goldilocks = { path = "../goldilocks", version = "0.1.5-succinct" }
p3-mersenne-31 = { path = "../mersenne-31", version = "0.1.5-succinct" }
p3-mds = { path = "../mds", version = "0.1.5-succinct" }
p3-merkle-tree = { path = "../merkle-tree", version = "0.1.5-succinct" }
p3-poseidon2 = { path = "../poseidon2", version = "0.1.5-succinct" }
p3-symmetric = { path = "../symmetric", version = "0.1.5-succinct" }
criterion = "0.5.1"
rand = "0.8.5"
rand_chacha = "0.3.1"

[[bench]]
name = "fold_even_odd"
harness = false
