[package]
name = "p3-merkle-tree"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field.workspace = true
p3-matrix.workspace = true
p3-maybe-rayon.workspace = true
p3-symmetric.workspace = true
p3-commit.workspace = true
p3-util.workspace = true

itertools.workspace = true
rand.workspace = true
serde = { workspace = true, features = ["alloc"] }
tracing.workspace = true

[dev-dependencies]
p3-blake3.workspace = true
p3-keccak.workspace = true
p3-baby-bear.workspace = true
p3-mds.workspace = true
#p3-poseidon2.workspace = true
p3-rescue.workspace = true
criterion.workspace = true

[features]
parallel = [
    "p3-matrix/parallel",
    "p3-maybe-rayon/parallel",
    "p3-commit/parallel",
]

[[bench]]
name = "merkle_tree"
harness = false
