[package]
name = "p3-merkle-tree"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = { path = "../field" }
p3-matrix = { path = "../matrix" }
p3-symmetric = { path = "../symmetric" }
p3-commit = { path = "../commit" }
p3-util = { path = "../util" }
itertools = "0.10.5"

[dev-dependencies]
p3-keccak = { path = "../keccak" }
rand = "0.8.5"
