[package]
name = "p3-merkle-tree"
description = "Plonky3 is a toolkit for implementing polynomial IOPs (PIOPs), such as PLONK and STARKs."
version = "0.1.5-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = { path = "../field", version = "0.1.5-succinct" }
p3-matrix = { path = "../matrix", version = "0.1.5-succinct" }
p3-maybe-rayon = { path = "../maybe-rayon", version = "0.1.5-succinct" }
p3-symmetric = { path = "../symmetric", version = "0.1.5-succinct" }
p3-commit = { path = "../commit", version = "0.1.5-succinct" }
p3-util = { path = "../util", version = "0.1.5-succinct" }
itertools = "0.12.0"
tracing = "0.1.37"
serde = { version = "1.0", default-features = false, features = ["alloc"] }

[dev-dependencies]
p3-blake3 = { path = "../blake3", version = "0.1.5-succinct" }
p3-keccak = { path = "../keccak", version = "0.1.5-succinct" }
p3-baby-bear = { path = "../baby-bear", version = "0.1.5-succinct" }
p3-mds = { path = "../mds", version = "0.1.5-succinct" }
p3-poseidon2 = { path = "../poseidon2", version = "0.1.5-succinct" }
p3-rescue = { path = "../rescue", version = "0.1.5-succinct" }
criterion = "0.5.1"
rand = "0.8.5"

[[bench]]
name = "merkle_tree"
harness = false
