[package]
name = "p3-merkle-tree"
description = "A Merkle tree implementation providing commitment scheme functionality for cryptographic proofs."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
p3-commit.workspace = true
p3-field.workspace = true
p3-matrix.workspace = true
p3-maybe-rayon.workspace = true
p3-symmetric.workspace = true
p3-util.workspace = true

itertools.workspace = true
rand.workspace = true
serde = { workspace = true, features = ["alloc"] }
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
p3-baby-bear = { path = "../baby-bear" }
p3-blake3 = { path = "../blake3" }
p3-goldilocks = { path = "../goldilocks" }
p3-keccak = { path = "../keccak" }
p3-mds = { path = "../mds" }
p3-rescue = { path = "../rescue" }

criterion.workspace = true

[[bench]]
name = "merkle_tree"
harness = false

[lints]
workspace = true
