[package]
name = "p3-merkle-tree"
description = "A Merkle tree implementation providing commitment scheme functionality for cryptographic proofs."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
p3-field = { workspace = true }
p3-matrix = { workspace = true }
p3-maybe-rayon = { workspace = true }
p3-symmetric = { workspace = true }
p3-commit = { workspace = true }
p3-util = { workspace = true }
itertools = "0.12.0"
tracing = "0.1.37"
serde = { version = "1.0", default-features = false, features = ["alloc"] }

[dev-dependencies]
p3-blake3 = { workspace = true }
p3-keccak = { workspace = true }
p3-baby-bear = { workspace = true }
p3-mds = { workspace = true }
p3-poseidon2 = { workspace = true }
p3-rescue = { workspace = true }
criterion = "0.5.1"
rand = "0.8.5"

[[bench]]
name = "merkle_tree"
harness = false
