[package]
name = "p3-blake3"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-symmetric = { path = "../symmetric" }
p3-util = { path = "../util" }
blake3 = "1.5"

[features]
neon = ["blake3/neon"]
parallel = ["blake3/rayon"]
