[package]
name = "p3-blake3"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
p3-symmetric.workspace = true
p3-util.workspace = true

blake3.workspace = true

[features]
neon = ["blake3/neon"]
parallel = ["blake3/rayon"]
