[package]
name = "p3-blake3"
description = "Plonky3 is a toolkit for implementing polynomial IOPs (PIOPs), such as PLONK and STARKs."
version = "0.1.5-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-symmetric = { path = "../symmetric", version = "0.1.5-succinct" }
blake3 = "1.5"

[features]
neon = ["blake3/neon"]
parallel = ["blake3/rayon"]
