[package]
name = "p3-ldt"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-challenger = { path = "../challenger" }
p3-commit = { path = "../commit" }
p3-field = { path = "../field" }
p3-matrix = { path = "../matrix" }
