[package]
name = "p3-bn254-fr"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = { path = "../field" }
p3-poseidon2 = { path = "../poseidon2" }
p3-symmetric = { path = "../symmetric" }

ff = { workspace = true, features = ["derive", "derive_bits"] }
num-bigint.workspace = true
rand.workspace = true
serde = { workspace = true, features = ["derive"] }
halo2curves = { workspace = true, features = ["bits", "derive_serde"] }

[dev-dependencies]
p3-field-testing = { path = "../field-testing" }

criterion.workspace = true
num-traits.workspace = true
serde_json.workspace = true
zkhash.workspace = true

[features]
default = []
table = [
    "halo2curves/bn256-table",
] # Generate cached table of [0, 2^16) in Bn254Fr at compile time
asm = ["halo2curves/asm"]

[[bench]]
name = "bench_field"
harness = false
