[package]
name = "p3-bn254-fr"
description = "Plonky3 is a toolkit for implementing polynomial IOPs (PIOPs), such as PLONK and STARKs."
version = "0.1.5-succinct"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = { path = "../field", version = "0.1.5-succinct" }
p3-poseidon2 = { path = "../poseidon2", version = "0.1.5-succinct" }
p3-symmetric = { path = "../symmetric", version = "0.1.5-succinct" }

ff = { version = "0.13", features = ["derive", "derive_bits"] }
num-bigint = { version = "0.4.3", default-features = false }
rand = "0.8.5"
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dev-dependencies]
p3-field-testing = { path = "../field-testing", version = "0.1.5-succinct" }

criterion = "0.5.1"
num-traits = "0.2.16"
serde_json = "1.0.113"
zkhash = { git = "https://github.com/HorizenLabs/poseidon2" }

[[bench]]
name = "bench_field"
harness = false
