[package]
name = "p3-poseidon"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field.workspace = true
p3-mds.workspace = true
p3-symmetric.workspace = true

p3-maybe-rayon = { workspace = true, optional = true }

rand.workspace = true

[dev-dependencies]
p3-baby-bear.workspace = true
p3-goldilocks.workspace = true
p3-mersenne-31.workspace = true

criterion.workspace = true

[features]
parallel = ["p3-maybe-rayon/parallel"]
# Benchmarking
nightly-features = [
    "p3-baby-bear/nightly-features",
    "p3-goldilocks/nightly-features",
    "p3-mersenne-31/nightly-features",
]

[[bench]]
name = "poseidon"
harness = false
