[package]
name = "p3-sha256"
description = "Plonky3 hash trait implementations for the SHA2-256 hash function."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
p3-symmetric.workspace = true
p3-util.workspace = true
sha2 = { workspace = true, features = ["compress"] }

[features]
default = []
asm = [
    "sha2/asm",
] # Enable either x86 or aarch assembly implementation based on target.
force-soft = [
    "sha2/force-soft",
] # Force software implementation (default if "asm" feature is not enabled).

[dev-dependencies]
hex-literal.workspace = true
