[package]
name = "p3-uni-stark"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
p3-air = { path = "../air", version = "0.3.0" }
p3-field = { path = "../field", version = "0.3.0" }
p3-challenger = { path = "../challenger", version = "0.3.0" }
p3-commit = { path = "../commit", version = "0.3.0" }
p3-dft = { path = "../dft", version = "0.3.0" }
p3-matrix = { path = "../matrix", version = "0.3.0" }
p3-maybe-rayon = { path = "../maybe-rayon" }
p3-util = { path = "../util", version = "0.3.0" }
itertools = "0.13.0"
tracing = "0.1.37"
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }

[dev-dependencies]
p3-baby-bear = { path = "../baby-bear" }
p3-commit = { path = "../commit", features = ["test-utils"] }
p3-circle = { path = "../circle" }
p3-fri = { path = "../fri" }
p3-keccak = { path = "../keccak" }
p3-mds = { path = "../mds" }
p3-merkle-tree = { path = "../merkle-tree" }
p3-mersenne-31 = { path = "../mersenne-31" }
p3-poseidon2 = { path = "../poseidon2" }
p3-symmetric = { path = "../symmetric" }
rand = "0.8.5"
postcard = { version = "1.0.0", default-features = false, features = ["alloc"] }
