[package]
name = "p3-uni-stark"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-air = { path = "../air" }
p3-field = { path = "../field" }
p3-challenger = { path = "../challenger" }
p3-commit = { path = "../commit" }
p3-dft = { path = "../dft" }
p3-matrix = { path = "../matrix" }
p3-maybe-rayon = { path = "../maybe-rayon" }
p3-util = { path = "../util" }
itertools = "0.12.0"
tracing = "0.1.37"

[dev-dependencies]
p3-baby-bear = { path = "../baby-bear" }
p3-fri = { path = "../fri" }
p3-ldt = { path = "../ldt" }
p3-mds = { path = "../mds" }
p3-merkle-tree = { path = "../merkle-tree" }
p3-goldilocks = { path = "../goldilocks" }
p3-mersenne-31 = { path = "../mersenne-31" }
p3-poseidon2 = { path = "../poseidon2" }
p3-symmetric = { path = "../symmetric" }
rand = "0.8.5"
tracing-subscriber = { version = "0.3.17", features = ["std", "env-filter"] }
tracing-forest = { version = "0.1.6", features = ["ansi", "smallvec"] }
