[package]
name = "p3-uni-stark"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-air = { path = "../air" }
p3-field = { path = "../field" }
p3-challenger = { path = "../challenger" }
p3-commit = { path = "../commit" }
p3-lde = { path = "../lde" }
p3-matrix = { path = "../matrix" }
p3-maybe-rayon = { path = "../maybe-rayon" }
p3-util = { path = "../util" }

[dev-dependencies]
p3-fri = { path = "../fri" }
p3-ldt = { path = "../ldt" }
p3-merkle-tree = { path = "../merkle-tree" }
p3-goldilocks = { path = "../goldilocks" }
p3-mersenne-31 = { path = "../mersenne-31" }
p3-poseidon = { path = "../poseidon" }
p3-symmetric = { path = "../symmetric" }
rand = "0.8.5"
