[package]
name = "p3-mds"
description = "A collection of methods allowing for fast multiplication by MDS matrices."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
p3-dft = { workspace = true }
p3-field = { workspace = true }
p3-matrix = { workspace = true }
p3-symmetric = { workspace = true }
p3-util = { workspace = true }
rand = { version = "0.8.5", features = ["min_const_gen"] }
itertools = "0.12.0"

[dev-dependencies]
criterion = "0.5.1"
p3-baby-bear = { workspace = true }
p3-goldilocks = { workspace = true }
p3-mersenne-31 = { workspace = true }

[[bench]]
name = "mds"
harness = false
