[package]
name = "p3-mds"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-dft = { path = "../dft", version = "0.3.0" }
p3-field = { path = "../field", version = "0.3.0" }
p3-matrix = { path = "../matrix", version = "0.3.0" }
p3-symmetric = { path = "../symmetric", version = "0.3.0" }
p3-util = { path = "../util", version = "0.3.0" }
rand = { version = "0.8.5", features = ["min_const_gen"] }
itertools = "0.13.0"

[dev-dependencies]
criterion = "0.5.1"
p3-baby-bear = { path = "../baby-bear", version = "0.3.0" }
p3-goldilocks = { path = "../goldilocks", version = "0.3.0" }
p3-mersenne-31 = { path = "../mersenne-31", version = "0.3.0" }

[[bench]]
name = "mds"
harness = false
