[package]
name = "p3-blake3-air"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
p3-air.workspace = true
p3-field.workspace = true
p3-matrix.workspace = true
p3-maybe-rayon.workspace = true
rand.workspace = true
tracing.workspace = true
itertools.workspace = true

[dev-dependencies]
p3-baby-bear.workspace = true
p3-blake3.workspace = true
p3-koala-bear.workspace = true
p3-challenger.workspace = true
p3-circle.workspace = true
p3-commit.workspace = true
p3-dft.workspace = true
p3-fri.workspace = true
p3-goldilocks.workspace = true
p3-keccak.workspace = true
p3-mds.workspace = true
p3-merkle-tree.workspace = true
p3-mersenne-31.workspace = true
p3-monty-31.workspace = true
p3-poseidon.workspace = true
p3-poseidon2.workspace = true
p3-sha256.workspace = true
p3-symmetric.workspace = true
p3-uni-stark.workspace = true
tracing-subscriber = { workspace = true, features = ["std", "env-filter"] }
tracing-forest = { workspace = true, features = ["ansi", "smallvec"] }

[features]
parallel = ["p3-maybe-rayon/parallel"]
asm = ["p3-sha256/asm"]
nightly-features = [
    "p3-goldilocks/nightly-features",
    "p3-monty-31/nightly-features",
    "p3-baby-bear/nightly-features",
    "p3-koala-bear/nightly-features",
    "p3-mersenne-31/nightly-features",
]
