[package]
name = "p3-symmetric"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = { path = "../field" }
itertools = "0.13.0"
serde = { version = "1.0", default-features = false, features = ["alloc"] }
