[package]
name = "p3-symmetric"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
p3-field.workspace = true

itertools.workspace = true
serde = { workspace = true, features = ["alloc"] }

[dev-dependencies]
p3-koala-bear.workspace = true
