[package]
name = "p3-stir"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-challenger.workspace = true
p3-commit.workspace = true
p3-coset.workspace = true
p3-dft.workspace = true
p3-field.workspace = true
p3-interpolation.workspace = true
p3-matrix.workspace = true
p3-maybe-rayon.workspace = true
p3-poly.workspace = true
p3-util.workspace = true
itertools.workspace = true
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }

[dev-dependencies]
p3-baby-bear.workspace = true
p3-bn254-fr.workspace = true
p3-circle.workspace = true
p3-dft.workspace = true
p3-goldilocks.workspace = true
p3-keccak.workspace = true
p3-poly = { workspace = true, features = ["test-utils"] }
p3-mersenne-31.workspace = true
p3-mds.workspace = true
p3-merkle-tree.workspace = true
p3-poseidon2.workspace = true
p3-symmetric.workspace = true
criterion = "0.5.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
