[package]
name = "p3-field"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
p3-util.workspace = true
p3-maybe-rayon.workspace = true
num-bigint.workspace = true
paste.workspace = true
tracing.workspace = true

itertools.workspace = true
rand.workspace = true
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
p3-baby-bear.workspace = true
p3-goldilocks.workspace = true