[package]
name = "p3-field"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lints]
workspace = true

[dependencies]
p3-util.workspace = true
p3-maybe-rayon.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
num-integer.workspace = true
nums.workspace = true
tracing.workspace = true

itertools.workspace = true
rand.workspace = true
serde = { workspace = true, features = ["derive"] }
