[package]
name = "p3-mersenne-31"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
criterion = "0.5"
p3-field = { path = "../field" }
rand = "0.8.5"

[[bench]]
name = "inverse"
harness = false
