[package]
name = "p3-mersenne-31"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
nightly-features = []

[dependencies]
itertools = "0.13.0"
p3-dft = { path = "../dft", version = "0.3.0" }
p3-field = { path = "../field", version = "0.3.0" }
p3-matrix = { path = "../matrix", version = "0.3.0" }
p3-mds = { path = "../mds", version = "0.3.0" }
p3-maybe-rayon = { path = "../maybe-rayon" }
p3-poseidon2 = { path = "../poseidon2" }
p3-symmetric = { path = "../symmetric", version = "0.3.0" }
p3-util = { path = "../util", version = "0.3.0" }
num-bigint = { version = "0.4.3", default-features = false }
rand = "0.8.5"
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dev-dependencies]
criterion = "0.5"
p3-field-testing = { path = "../field-testing" }
rand_chacha = "0.3.1"
rand_xoshiro = "0.6.0"

[[bench]]
name = "bench_field"
harness = false

[[bench]]
name = "extension"
harness = false
