[package]
name = "p3-mersenne-31"
description = "An implementation of the Mersenne31 prime field F_p, where p = 2^31 - 1."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
itertools = "0.12.0"
p3-dft = { workspace = true }
p3-field = { workspace = true }
p3-matrix = { workspace = true }
p3-mds = { workspace = true }
p3-maybe-rayon = { workspace = true }
p3-poseidon2 = { workspace = true }
p3-symmetric = { workspace = true }
p3-util = { workspace = true }
num-bigint = { version = "0.4.3", default-features = false }
rand = "0.8.5"
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dev-dependencies]
criterion = "0.5"
p3-field-testing = { workspace = true }
rand_chacha = "0.3.1"
rand_xoshiro = "0.6.0"

[[bench]]
name = "bench_field"
harness = false

[[bench]]
name = "extension"
harness = false
