[package]
name = "p3-field-testing"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-dft = { path="../dft" }
p3-field.workspace = true
p3-matrix = { path="../matrix" }
rand = { workspace = true, features = ["min_const_gen"] }
rand_chacha.workspace = true
num-bigint.workspace = true
num-traits.workspace = true

[dev-dependencies]
p3-baby-bear.workspace = true
