[package]
name = "p3-field-testing"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
p3-dft.workspace = true
p3-field.workspace = true
p3-matrix.workspace = true
rand.workspace = true
criterion.workspace = true
num-bigint.workspace = true
p3-util.workspace = true

[dev-dependencies]
p3-baby-bear.workspace = true
