[package]
name = "p3-field-testing"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
p3-dft = { path="../dft", version = "0.3.0" }
p3-field = { path = "../field", version = "0.3.0" }
p3-matrix = { path = "../matrix", version = "0.3.0" }
rand = { version = "0.8.5", features = ["min_const_gen"] }
rand_chacha = "0.3.1"
criterion = "0.5.1"
num-bigint = { version = "0.4.3", default-features = false }
num-traits = "0.2.19"

[dev-dependencies]
p3-baby-bear = { path = "../baby-bear" }
